%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/melodic/.*$
%global __requires_exclude_from ^/opt/ros/melodic/.*$

Name:           ros-melodic-cis-camera
Version:        0.0.3
Release:        1%{?dist}
Summary:        ROS cis_camera package

License:        BSD
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-melodic-camera-info-manager
Requires:       ros-melodic-cv-bridge
Requires:       ros-melodic-dynamic-reconfigure
Requires:       ros-melodic-image-transport
Requires:       ros-melodic-jsk-rviz-plugins
Requires:       ros-melodic-libuvc
Requires:       ros-melodic-nodelet
Requires:       ros-melodic-pcl-ros
Requires:       ros-melodic-pluginlib
Requires:       ros-melodic-rgbd-launch
Requires:       ros-melodic-roscpp
Requires:       ros-melodic-rqt-reconfigure
Requires:       ros-melodic-rviz
Requires:       ros-melodic-sensor-msgs
Requires:       ros-melodic-tf
Requires:       ros-melodic-tf-conversions
BuildRequires:  ros-melodic-camera-info-manager
BuildRequires:  ros-melodic-catkin
BuildRequires:  ros-melodic-cv-bridge
BuildRequires:  ros-melodic-dynamic-reconfigure
BuildRequires:  ros-melodic-image-transport
BuildRequires:  ros-melodic-libuvc
BuildRequires:  ros-melodic-nodelet
BuildRequires:  ros-melodic-pcl-ros
BuildRequires:  ros-melodic-pluginlib
BuildRequires:  ros-melodic-roscpp
BuildRequires:  ros-melodic-roslaunch
BuildRequires:  ros-melodic-rostest
BuildRequires:  ros-melodic-sensor-msgs
BuildRequires:  ros-melodic-tf
BuildRequires:  ros-melodic-tf-conversions

%description
The cis_camera package

%prep
%autosetup

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_LIBDIR="lib" \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
    -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
    -DCATKIN_BUILD_BINARY_PACKAGE="1" \
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
%make_install -C obj-%{_target_platform}

%files
/opt/ros/melodic

%changelog
* Thu Nov 14 2019 Yosuke Yamamoto <yamamoto.yosuke@opensource-robotics.tokyo.jp> - 0.0.3-1
- Autogenerated by Bloom

* Sun Nov 10 2019 Yosuke Yamamoto <yamamoto.yosuke@opensource-robotics.tokyo.jp> - 0.0.2-1
- Autogenerated by Bloom

