image_width: 1280
image_height: 960
camera_name: camera
camera_matrix:
  rows: 3
  cols: 3
  data: [ 775.3, 0.0, 620.0, 0.0, 773.5, 480.0, 0.0, 0.0, 1.0 ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [ -0.3404, 0.1460, 0.0005811, 0.0001660, -0.03137 ]
rectification_matrix:
  rows: 3
  cols: 3
  data: [ 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0 ]
projection_matrix:
  rows: 3
  cols: 4
  data: [ 583.2, 0.0, 648.0, 0.0, 0.0, 659.97, 486.9, 0.0, 0.0, 0.0, 1.0, 0.0 ]
